version: "3.9"
services:
  envoy:
    image: envoyproxy/envoy:v1.20-latest
    entrypoint: /usr/local/bin/envoy
    command:  -c /etc/envoy/envoy.yaml -l trace --log-path /tmp/envoy_info.log
    networks:
      grpcstack:
        aliases:
          - envoy
    ports:
      - "8099:8099" # Envoy's gRPC API
      - "9901:9901" # Envoy's HTTP API
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
  grpcserver:
    image: golang:latest
    working_dir: /run
    entrypoint: go run .
    networks:
      grpcstack:
        aliases:
          - grpcserver
    expose:
      - "9090"
    ports:
      - "9090:9090" # gRPC server's gRPC API
    volumes: 
      - ./grpc_server:/run
    # stdin_open: true
    tty: true
  webpack:
    image: node:latest
    working_dir: /app
    entrypoint: ["/app/start.sh"]
    networks:
      grpcstack:
        aliases:
          - webpack
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./webapp-template:/app

networks:
  grpcstack:
